use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::paths::NetweftPaths;
use crate::plan::nas_permission::ResolvedNasPermissionPlan;

pub fn render_nas_permissions(
    plan: &ResolvedNasPermissionPlan,
    paths: &NetweftPaths,
) -> Result<PathBuf> {
    let nas = plan
        .nas
        .as_deref()
        .context("NAS permission rendering requires a NAS target")?;
    let output = paths
        .generated_dir
        .join(&plan.location)
        .join("nas")
        .join(nas)
        .join("nfs-permissions");
    let parent = output
        .parent()
        .context("NAS permission output has no parent")?;
    fs::create_dir_all(parent)?;
    let temp = parent.join(format!(".nfs-permissions-{}.tmp", std::process::id()));
    if temp.exists() {
        fs::remove_dir_all(&temp)?;
    }
    fs::create_dir_all(&temp)?;

    write(&temp.join("action-plan.txt"), &action_plan(plan))?;
    write(&temp.join("manifest.txt"), &manifest(plan))?;

    if output.exists() {
        fs::remove_dir_all(&output)?;
    }
    fs::rename(&temp, &output)?;
    Ok(output)
}

fn action_plan(plan: &ResolvedNasPermissionPlan) -> String {
    let mut out = String::from(
        "Generated by Netweft. Apply these permissions in Synology DSM.\n\n\
Control Panel -> Shared Folder -> select share -> Edit -> NFS Permissions\n\n",
    );

    for permission in &plan.permissions {
        out.push_str(&format!(
            "Permission: {}\nNAS: {} ({})\nShare: {}\nClient host: {}\nClient IPv4: {}\nPrivilege: {}\nSquash: {}\nSecurity: {}\n\n",
            permission.id,
            permission.nas,
            permission.nas_ipv4,
            permission.share,
            permission.client_host,
            permission.client_ipv4,
            permission.access.dsm_name(),
            permission.squash.dsm_name(),
            permission.security,
        ));
    }
    out
}

fn manifest(plan: &ResolvedNasPermissionPlan) -> String {
    let mut out = format!(
        "adapter=synology-nfs-permissions\nlocation={}\nnas={}\n",
        plan.location,
        plan.nas.as_deref().unwrap_or("none")
    );
    for permission in &plan.permissions {
        out.push_str(&format!(
            "permission={} share={} client_host={} client_ipv4={} access={} squash={} security={}\n",
            permission.id,
            permission.share,
            permission.client_host,
            permission.client_ipv4,
            permission.access.as_str(),
            permission.squash.as_str(),
            permission.security,
        ));
    }
    out
}

fn write(path: &Path, contents: &str) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("failed to write {}", path.display()))
}
