use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::model::{HostOsIpv4Mode, HostOsIpv6Mode};
use crate::paths::NetweftPaths;
use crate::plan::os_network::ResolvedOsNetworkPlan;

pub fn render_netplan(plan: &ResolvedOsNetworkPlan, paths: &NetweftPaths) -> Result<PathBuf> {
    let output = paths
        .generated_dir
        .join(&plan.location)
        .join("hosts")
        .join(&plan.host)
        .join("netplan");
    let parent = output.parent().context("Netplan output has no parent")?;
    fs::create_dir_all(parent)?;

    let temp = parent.join(format!(".netplan-{}.tmp", std::process::id()));
    if temp.exists() {
        fs::remove_dir_all(&temp)?;
    }

    fs::create_dir_all(temp.join("etc/netplan"))?;
    fs::create_dir_all(temp.join("etc/cloud/cloud.cfg.d"))?;

    write(
        &temp.join("etc/netplan/60-netweft.yaml"),
        &netplan_yaml(plan),
    )?;
    write(
        &temp.join("etc/cloud/cloud.cfg.d/99-disable-network-config.cfg"),
        "network: {config: disabled}\n",
    )?;
    write(&temp.join("apply.sh"), &apply_script(plan))?;
    write(&temp.join("rollback.sh"), &rollback_script())?;
    write(&temp.join("manifest.txt"), &manifest(plan))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(temp.join("apply.sh"), fs::Permissions::from_mode(0o755))?;
        fs::set_permissions(temp.join("rollback.sh"), fs::Permissions::from_mode(0o755))?;
    }

    if output.exists() {
        fs::remove_dir_all(&output)?;
    }
    fs::rename(&temp, &output)?;
    Ok(output)
}

fn netplan_yaml(plan: &ResolvedOsNetworkPlan) -> String {
    let dhcp4 = matches!(plan.ipv4_mode, HostOsIpv4Mode::Dhcp);
    let accept_ra = matches!(plan.ipv6_mode, HostOsIpv6Mode::RouterAdvertised);

    format!(
        "# Generated by Netweft. Do not edit.\nnetwork:\n  version: 2\n  renderer: {}\n  ethernets:\n    {}:\n      dhcp4: {}\n      accept-ra: {}\n",
        plan.renderer.as_str(),
        plan.interface,
        yaml_bool(dhcp4),
        yaml_bool(accept_ra),
    )
}

fn apply_script(plan: &ResolvedOsNetworkPlan) -> String {
    let expected_ipv4 = plan
        .expected_ipv4
        .map(|address| address.to_string())
        .unwrap_or_default();

    format!(
        r#"#!/usr/bin/env bash
set -euo pipefail

stage_dir="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
backup_dir="/var/backups/netweft/netplan-$(date +%Y%m%d-%H%M%S)"
interface={interface}
expected_ipv4={expected_ipv4}

restore() {{
  echo "Restoring previous Netplan configuration from $backup_dir" >&2
  sudo rm -rf /etc/netplan
  sudo cp -a "$backup_dir/netplan" /etc/netplan
  if [ -f "$backup_dir/99-disable-network-config.cfg" ]; then
    sudo install -m 0644 "$backup_dir/99-disable-network-config.cfg" \
      /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  else
    sudo rm -f /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  fi
  sudo netplan generate
  sudo netplan apply
}}

sudo mkdir -p "$backup_dir"
sudo cp -a /etc/netplan "$backup_dir/netplan"
if [ -f /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg ]; then
  sudo cp -a /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg "$backup_dir/"
fi

trap restore ERR INT TERM HUP

sudo find /etc/netplan -maxdepth 1 -type f \
  \( -name '*.yaml' -o -name '*.yml' \) -delete
sudo install -m 0600 \
  "$stage_dir/etc/netplan/60-netweft.yaml" \
  /etc/netplan/60-netweft.yaml
sudo install -m 0644 \
  "$stage_dir/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg" \
  /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

sudo netplan generate

echo
echo "Netplan will now enter guarded trial mode."
echo "Confirm the configuration when prompted if SSH remains healthy."
echo
sudo netplan try --timeout 60

ip -4 address show dev "$interface" | grep -Fq "inet $expected_ipv4/"
ip -4 route show default dev "$interface" | grep -q '^default '
ip -6 route show default dev "$interface" | grep -q '^default '

if ip -6 address show dev "$interface" | grep -Fq '2603:8001:a000:100::d00d/64'; then
  echo "obsolete static IPv6 address is still present" >&2
  exit 1
fi

trap - ERR INT TERM HUP

echo "Applied Netweft Netplan configuration."
echo "Backup: $backup_dir"
"#,
        interface = shell_word(&plan.interface),
        expected_ipv4 = shell_word(&expected_ipv4),
    )
}

fn rollback_script() -> String {
    r#"#!/usr/bin/env bash
set -euo pipefail

backup=${1:?usage: rollback.sh /var/backups/netweft/netplan-TIMESTAMP}

sudo rm -rf /etc/netplan
sudo cp -a "$backup/netplan" /etc/netplan

if [ -f "$backup/99-disable-network-config.cfg" ]; then
  sudo install -m 0644 "$backup/99-disable-network-config.cfg" \
    /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
else
  sudo rm -f /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
fi

sudo netplan generate
sudo netplan apply

echo "Restored Netplan configuration from $backup"
"#
    .to_owned()
}

fn manifest(plan: &ResolvedOsNetworkPlan) -> String {
    format!(
        "adapter=netplan\nlocation={}\nhost={}\ninterface={}\nipv4_mode={}\nexpected_ipv4={}\nipv6_mode={}\n",
        plan.location,
        plan.host,
        plan.interface,
        plan.ipv4_mode.as_str(),
        plan.expected_ipv4
            .map(|value| value.to_string())
            .unwrap_or_default(),
        plan.ipv6_mode.as_str(),
    )
}

fn yaml_bool(value: bool) -> &'static str {
    if value { "true" } else { "false" }
}

fn shell_word(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn write(path: &Path, contents: &str) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("failed to write {}", path.display()))
}
