use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::paths::NetweftPaths;
use crate::plan::proxmox_storage::{ResolvedProxmoxStorage, ResolvedProxmoxStoragePlan};

pub fn render_proxmox_storage(
    plan: &ResolvedProxmoxStoragePlan,
    paths: &NetweftPaths,
) -> Result<PathBuf> {
    let output = paths
        .generated_dir
        .join(&plan.location)
        .join("hosts")
        .join(&plan.host)
        .join("proxmox-storage");
    let parent = output
        .parent()
        .context("Proxmox storage output has no parent")?;
    fs::create_dir_all(parent)?;
    let temp = parent.join(format!(".proxmox-storage-{}.tmp", std::process::id()));
    if temp.exists() {
        fs::remove_dir_all(&temp)?;
    }
    fs::create_dir_all(&temp)?;

    write(&temp.join("storage.cfg.fragment"), &storage_fragment(plan))?;
    write(&temp.join("apply.sh"), &apply_script(plan))?;
    write(&temp.join("rollback.sh"), &rollback_script())?;
    write(&temp.join("manifest.txt"), &manifest(plan))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(temp.join("apply.sh"), fs::Permissions::from_mode(0o755))?;
        fs::set_permissions(temp.join("rollback.sh"), fs::Permissions::from_mode(0o755))?;
    }

    if output.exists() {
        fs::remove_dir_all(&output)?;
    }
    fs::rename(&temp, &output)?;
    Ok(output)
}

fn storage_fragment(plan: &ResolvedProxmoxStoragePlan) -> String {
    let mut out = String::from("# Generated by Netweft. Do not edit.\n");
    for storage in &plan.storages {
        out.push_str(&format!(
            "\nnfs: {}\n\texport {}\n\tpath {}\n\tserver {}\n\tcontent {}\n\toptions {}\n",
            storage.storage_id,
            storage.export,
            storage.mount_path.display(),
            storage.server_ipv4,
            storage.content.join(","),
            storage.options.join(","),
        ));
        if let Some(prune) = &storage.prune_backups {
            out.push_str(&format!("\tprune-backups {prune}\n"));
        }
    }
    out
}

fn apply_script(plan: &ResolvedProxmoxStoragePlan) -> String {
    let mut out = String::from("#!/usr/bin/env bash\nset -euo pipefail\n\n");
    out.push_str("backup_dir=\"/root/netweft-backups/proxmox-storage-$(date +%Y%m%d-%H%M%S)\"\n");
    out.push_str(
        "mkdir -p \"$backup_dir\"\ncp -a /etc/pve/storage.cfg \"$backup_dir/storage.cfg\"\n\n",
    );

    for storage in &plan.storages {
        let add_arguments = pvesm_add_arguments(storage);
        let set_arguments = pvesm_set_arguments(storage);
        out.push_str(&format!(
            "if pvesm status | awk 'NR > 1 {{print $1}}' | grep -Fxq {}; then
  pvesm set {} {}
else
  pvesm add nfs {} {}
fi
",
            shell_quote(&storage.storage_id),
            shell_quote(&storage.storage_id),
            set_arguments,
            shell_quote(&storage.storage_id),
            add_arguments,
        ));
        out.push_str(&format!(
            "pvesm status | awk -v id={} 'NR == 1 || $1 == id'\n\n",
            shell_quote(&storage.storage_id)
        ));
    }
    out.push_str("echo \"Applied Netweft Proxmox storage plan. Backup: $backup_dir\"\n");
    out
}

fn pvesm_add_arguments(storage: &ResolvedProxmoxStorage) -> String {
    let mut args = vec![
        format!("--server {}", shell_quote(&storage.server_ipv4.to_string())),
        format!("--export {}", shell_quote(&storage.export)),
        format!(
            "--path {}",
            shell_quote(&storage.mount_path.display().to_string())
        ),
    ];
    args.extend(pvesm_mutable_arguments(storage));
    args.join(" ")
}

fn pvesm_set_arguments(storage: &ResolvedProxmoxStorage) -> String {
    pvesm_mutable_arguments(storage).join(" ")
}

fn pvesm_mutable_arguments(storage: &ResolvedProxmoxStorage) -> Vec<String> {
    let mut args = vec![
        format!("--content {}", shell_quote(&storage.content.join(","))),
        format!("--options {}", shell_quote(&storage.options.join(","))),
    ];

    if let Some(prune_backups) = &storage.prune_backups {
        args.push(format!("--prune-backups {}", shell_quote(prune_backups)));
    }

    args
}

fn rollback_script() -> String {
    "#!/usr/bin/env bash\nset -euo pipefail\n\nbackup=${1:?usage: rollback.sh /root/netweft-backups/proxmox-storage-TIMESTAMP/storage.cfg}\ninstall -m 0640 \"$backup\" /etc/pve/storage.cfg\npvesm status\n".to_owned()
}

fn manifest(plan: &ResolvedProxmoxStoragePlan) -> String {
    let mut out = format!(
        "adapter=proxmox-storage\nlocation={}\nhost={}\n",
        plan.location, plan.host
    );
    for storage in &plan.storages {
        out.push_str(&format!(
            "storage={} storage_id={} server_host={} server_ipv4={} export={} path={} content={} options={}\n",
            storage.id,
            storage.storage_id,
            storage.server_host,
            storage.server_ipv4,
            storage.export,
            storage.mount_path.display(),
            storage.content.join(","),
            storage.options.join(","),
        ));
    }
    out
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn write(path: &Path, contents: &str) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("failed to write {}", path.display()))
}
