use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::model::{GuestAddressMode, GuestKind};
use crate::paths::NetweftPaths;
use crate::plan::guest::{ResolvedGuest, ResolvedGuestPlan};

pub fn render_proxmox_guests(
    plan: &ResolvedGuestPlan,
    host: &str,
    paths: &NetweftPaths,
) -> Result<PathBuf> {
    let output = paths
        .generated_dir
        .join(&plan.location)
        .join("hosts")
        .join(host)
        .join("proxmox-guests");
    let parent = output
        .parent()
        .context("Proxmox guest output has no parent")?;
    fs::create_dir_all(parent)?;

    let temp = parent.join(format!(".proxmox-guests-{}.tmp", std::process::id()));
    if temp.exists() {
        fs::remove_dir_all(&temp)?;
    }
    fs::create_dir_all(&temp)?;

    let guests: Vec<_> = plan
        .guests
        .iter()
        .filter(|guest| guest.host == host)
        .collect();

    write(&temp.join("action-plan.txt"), &action_plan(host, &guests))?;
    write(&temp.join("apply.sh"), &apply_script(host, &guests))?;
    write(&temp.join("rollback.sh"), &rollback_script())?;
    write(&temp.join("manifest.txt"), &manifest(plan, host, &guests))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(temp.join("apply.sh"), fs::Permissions::from_mode(0o755))?;
        fs::set_permissions(temp.join("rollback.sh"), fs::Permissions::from_mode(0o755))?;
    }

    if output.exists() {
        fs::remove_dir_all(&output)?;
    }
    fs::rename(&temp, &output)?;
    Ok(output)
}

fn action_plan(host: &str, guests: &[&ResolvedGuest]) -> String {
    let mut out =
        format!("Generated by Netweft. Review before applying.\n\nProxmox host: {host}\n\n");
    for guest in guests {
        out.push_str(&format!(
            "{} {} ({})\n  VMID: {}\n  bridge: {}\n  MAC: {}\n  IPv4 reservation: {}\n  onboot: {}\n",
            match guest.kind {
                GuestKind::Vm => "VM",
                GuestKind::Lxc => "LXC",
            },
            guest.name,
            guest.host,
            guest.vmid,
            guest.bridge,
            guest.mac,
            guest.ipv4,
            guest.onboot,
        ));
        if let Some(startup) = &guest.startup {
            out.push_str(&format!("  startup: {startup}\n"));
        }
        for attachment in &guest.pci_devices {
            out.push_str(&format!(
                "  hostpci{}: {}\n",
                attachment.slot, attachment.device
            ));
        }
        for attachment in &guest.virtiofs {
            out.push_str(&format!(
                "  virtiofs{}: {} expose_acl={}\n",
                attachment.slot, attachment.directory, attachment.expose_acl
            ));
        }
        out.push('\n');
    }
    out
}

fn apply_script(host: &str, guests: &[&ResolvedGuest]) -> String {
    let mut out = String::from("#!/usr/bin/env bash\nset -euo pipefail\n\n");
    out.push_str(&format!(
        "backup_dir=\"/root/netweft-backups/proxmox-guests-{host}-$(date +%Y%m%d-%H%M%S)\"\nmkdir -p \"$backup_dir/lxc\" \"$backup_dir/qemu-server\"\n\n"
    ));

    for guest in guests {
        match guest.kind {
            GuestKind::Lxc => {
                out.push_str(&format!(
                    "pct config {vmid} >/dev/null\ncp -a /etc/pve/lxc/{vmid}.conf \"$backup_dir/lxc/{vmid}.conf\"\npct set {vmid} --net0 {net0} --onboot {onboot}\npct config {vmid} | grep -E '^(net0|onboot):'\n\n",
                    vmid = guest.vmid,
                    net0 = shell_quote(&lxc_net0(guest)),
                    onboot = bool_int(guest.onboot),
                ));
            }
            GuestKind::Vm => {
                out.push_str(&format!(
                    "qm config {vmid} >/dev/null\ncp -a /etc/pve/qemu-server/{vmid}.conf \"$backup_dir/qemu-server/{vmid}.conf\"\nqm set {vmid} --net0 {net0} --onboot {onboot}",
                    vmid = guest.vmid,
                    net0 = shell_quote(&vm_net0(guest)),
                    onboot = bool_int(guest.onboot),
                ));
                if let Some(startup) = &guest.startup {
                    out.push_str(&format!(" --startup {}", shell_quote(startup)));
                }
                for attachment in &guest.pci_devices {
                    out.push_str(&format!(
                        " --hostpci{} {}",
                        attachment.slot,
                        shell_quote(&attachment.device)
                    ));
                }
                for attachment in &guest.virtiofs {
                    let mut value = attachment.directory.clone();
                    if attachment.expose_acl {
                        value.push_str(",expose-acl=1");
                    }
                    out.push_str(&format!(
                        " --virtiofs{} {}",
                        attachment.slot,
                        shell_quote(&value)
                    ));
                }
                out.push_str(&format!(
                    "\nqm config {} | grep -E '^(net0|onboot|startup|hostpci[0-9]+|virtiofs[0-9]+):'\n\n",
                    guest.vmid
                ));
            }
        }
    }

    out.push_str("echo \"Applied Netweft Proxmox guest plan. Backup: $backup_dir\"\n");
    out
}

fn rollback_script() -> String {
    "#!/usr/bin/env bash\nset -euo pipefail\n\nbackup=${1:?usage: rollback.sh /root/netweft-backups/proxmox-guests-HOST-TIMESTAMP}\n\nfor file in \"$backup\"/lxc/*.conf; do\n  [ -e \"$file\" ] || continue\n  install -m 0640 \"$file\" \"/etc/pve/lxc/$(basename \"$file\")\"\ndone\n\nfor file in \"$backup\"/qemu-server/*.conf; do\n  [ -e \"$file\" ] || continue\n  install -m 0640 \"$file\" \"/etc/pve/qemu-server/$(basename \"$file\")\"\ndone\n\necho \"Restored Proxmox guest configuration from $backup\"\n".to_owned()
}

fn lxc_net0(guest: &ResolvedGuest) -> String {
    let mut parts = vec!["name=eth0".to_owned(), format!("bridge={}", guest.bridge)];
    if guest.firewall {
        parts.push("firewall=1".to_owned());
    }
    parts.push(format!("hwaddr={}", guest.mac));
    parts.push(match guest.address_mode {
        GuestAddressMode::ReservedDhcp => "ip=dhcp".to_owned(),
        GuestAddressMode::Static => format!("ip={}/24", guest.ipv4),
    });
    parts.push("ip6=auto".to_owned());
    parts.push("type=veth".to_owned());
    parts.join(",")
}

fn vm_net0(guest: &ResolvedGuest) -> String {
    let mut parts = vec![
        format!("virtio={}", guest.mac),
        format!("bridge={}", guest.bridge),
    ];
    if guest.firewall {
        parts.push("firewall=1".to_owned());
    }
    parts.join(",")
}

fn manifest(plan: &ResolvedGuestPlan, host: &str, guests: &[&ResolvedGuest]) -> String {
    let mut out = format!(
        "adapter=proxmox-guests\nlocation={}\nhost={host}\n",
        plan.location
    );
    for guest in guests {
        out.push_str(&format!(
            "guest={} kind={:?} vmid={} bridge={} mac={} ipv4={} onboot={}\n",
            guest.name, guest.kind, guest.vmid, guest.bridge, guest.mac, guest.ipv4, guest.onboot,
        ));
    }
    out
}

fn bool_int(value: bool) -> u8 {
    u8::from(value)
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn write(path: &Path, contents: &str) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("failed to write {}", path.display()))
}
