use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::paths::NetweftPaths;
use crate::plan::proxmox_sdn::ResolvedProxmoxSdnPlan;

pub fn render_proxmox_sdn(plan: &ResolvedProxmoxSdnPlan, paths: &NetweftPaths) -> Result<PathBuf> {
    let output = paths
        .generated_dir
        .join(&plan.location)
        .join("hosts")
        .join(&plan.host)
        .join("proxmox-sdn");
    let parent = output
        .parent()
        .context("Proxmox SDN output has no parent")?;
    fs::create_dir_all(parent)?;

    let temp = parent.join(format!(".proxmox-sdn-{}.tmp", std::process::id()));
    if temp.exists() {
        fs::remove_dir_all(&temp)?;
    }
    fs::create_dir_all(&temp)?;

    write(&temp.join("action-plan.txt"), &action_plan(plan))?;
    write(&temp.join("apply.sh"), &apply_script(plan))?;
    write(&temp.join("verify.sh"), &verify_script(plan))?;
    write(&temp.join("rollback.sh"), &rollback_script())?;
    write(&temp.join("manifest.txt"), &manifest(plan))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        for name in ["apply.sh", "verify.sh", "rollback.sh"] {
            fs::set_permissions(temp.join(name), fs::Permissions::from_mode(0o755))?;
        }
    }

    if output.exists() {
        fs::remove_dir_all(&output)?;
    }
    fs::rename(&temp, &output)?;
    Ok(output)
}

fn action_plan(plan: &ResolvedProxmoxSdnPlan) -> String {
    let mut out = format!(
        "Generated by Netweft. Review before applying.\n\nHost: {}\nLocation: {}\n\n",
        plan.host, plan.location
    );

    for zone in &plan.zones {
        out.push_str(&format!(
            "Zone {}: kind={} ipam={} dhcp={}\n",
            zone.name,
            zone.kind.as_str(),
            zone.ipam.as_str(),
            zone.dhcp.as_str(),
        ));
    }

    for vnet in &plan.vnets {
        out.push_str(&format!(
            "VNet {}: zone={} alias={}\n",
            vnet.name,
            vnet.zone,
            vnet.alias.as_deref().unwrap_or("none"),
        ));
        for subnet in &vnet.subnets {
            out.push_str(&format!(
                "  Subnet {}: gateway={} dhcp={}-{} snat={}\n",
                subnet.cidr, subnet.gateway, subnet.dhcp_start, subnet.dhcp_end, subnet.snat,
            ));
        }
    }

    out.push_str("\nThis plan does not modify vmbr0, vmbr1, or guest NIC assignments.\n");
    out
}

fn apply_script(plan: &ResolvedProxmoxSdnPlan) -> String {
    let mut out = String::from("#!/usr/bin/env bash\nset -euo pipefail\n\n");
    out.push_str(
        "backup_dir=\"/root/netweft-backups/proxmox-sdn-$(date +%Y%m%d-%H%M%S)\"\n\
         mkdir -p \"$backup_dir\"\n\
         cp -a /etc/pve/sdn \"$backup_dir/sdn\"\n\n",
    );

    for zone in &plan.zones {
        out.push_str(&format!(
            "if pvesh get /cluster/sdn/zones/{name} >/dev/null 2>&1; then\n\
             \tpvesh set /cluster/sdn/zones/{name} --type {kind} --ipam {ipam} --dhcp {dhcp}\n\
             else\n\
             \tpvesh create /cluster/sdn/zones --zone {name} --type {kind} --ipam {ipam} --dhcp {dhcp}\n\
             fi\n\n",
            name = zone.name,
            kind = zone.kind.as_str(),
            ipam = zone.ipam.as_str(),
            dhcp = zone.dhcp.as_str(),
        ));
    }

    for vnet in &plan.vnets {
        let alias = vnet.alias.as_deref().unwrap_or(&vnet.name);
        out.push_str(&format!(
            "if pvesh get /cluster/sdn/vnets/{name} >/dev/null 2>&1; then\n\
             \tpvesh set /cluster/sdn/vnets/{name} --zone {zone} --alias {alias}\n\
             else\n\
             \tpvesh create /cluster/sdn/vnets --vnet {name} --zone {zone} --alias {alias}\n\
             fi\n\n",
            name = vnet.name,
            zone = vnet.zone,
            alias = shell_word(alias),
        ));

        for subnet in &vnet.subnets {
            let range = format!(
                "start-address={},end-address={}",
                subnet.dhcp_start, subnet.dhcp_end
            );
            out.push_str(&format!(
                "if pvesh get /cluster/sdn/vnets/{vnet}/subnets/{id} >/dev/null 2>&1; then\n\
                 \tpvesh set /cluster/sdn/vnets/{vnet}/subnets/{id} --gateway {gateway} --snat {snat} --dhcp-range {range}\n\
                 else\n\
                 \tpvesh create /cluster/sdn/vnets/{vnet}/subnets --subnet {id} --type subnet --vnet {vnet} --gateway {gateway} --snat {snat} --dhcp-range {range}\n\
                 fi\n\n",
                vnet = vnet.name,
                id = subnet.id,
                gateway = subnet.gateway,
                snat = u8::from(subnet.snat),
                range = shell_word(&range),
            ));
        }
    }

    out.push_str(
        "pvesh set /cluster/sdn\n\
         systemctl is-active pve-sdn-commit.service >/dev/null || true\n\
         echo \"Applied Netweft Proxmox SDN plan. Backup: $backup_dir\"\n",
    );
    out
}

fn verify_script(plan: &ResolvedProxmoxSdnPlan) -> String {
    let mut out = String::from("#!/usr/bin/env bash\nset -euo pipefail\n\n");
    for zone in &plan.zones {
        out.push_str(&format!(
            "pvesh get /cluster/sdn/zones/{name} --output-format yaml\n",
            name = zone.name
        ));
    }
    for vnet in &plan.vnets {
        out.push_str(&format!(
            "pvesh get /cluster/sdn/vnets/{name} --output-format yaml\n\
             pvesh get /cluster/sdn/vnets/{name}/subnets --output-format yaml\n\
             ip -br address show {name}\n\
             ip route show dev {name}\n",
            name = vnet.name
        ));
    }
    out
}

fn rollback_script() -> String {
    r#"#!/usr/bin/env bash
set -euo pipefail

backup=${1:?usage: rollback.sh /root/netweft-backups/proxmox-sdn-TIMESTAMP}
source_dir="$backup/sdn"
target_dir="/etc/pve/sdn"

if [ ! -d "$source_dir" ]; then
  echo "missing SDN backup directory: $source_dir" >&2
  exit 1
fi

# Restore only declarative SDN configuration. Never remove the
# pmxcfs-managed /etc/pve/sdn directory or overwrite runtime state.
for name in zones.cfg vnets.cfg subnets.cfg controllers.cfg; do
  if [ -f "$source_dir/$name" ]; then
    cp -a "$source_dir/$name" "$target_dir/$name"
  else
    rm -f "$target_dir/$name"
  fi
done

pvesh set /cluster/sdn

echo "Restored Proxmox SDN configuration from $backup"
"#
    .to_owned()
}

fn manifest(plan: &ResolvedProxmoxSdnPlan) -> String {
    let mut out = format!(
        "adapter=proxmox-sdn\nlocation={}\nhost={}\n",
        plan.location, plan.host
    );
    for zone in &plan.zones {
        out.push_str(&format!(
            "zone={} kind={} ipam={} dhcp={}\n",
            zone.name,
            zone.kind.as_str(),
            zone.ipam.as_str(),
            zone.dhcp.as_str(),
        ));
    }
    for vnet in &plan.vnets {
        out.push_str(&format!(
            "vnet={} zone={} alias={}\n",
            vnet.name,
            vnet.zone,
            vnet.alias.as_deref().unwrap_or(""),
        ));
        for subnet in &vnet.subnets {
            out.push_str(&format!(
                "subnet={} cidr={} gateway={} dhcp_start={} dhcp_end={} snat={}\n",
                subnet.id,
                subnet.cidr,
                subnet.gateway,
                subnet.dhcp_start,
                subnet.dhcp_end,
                subnet.snat,
            ));
        }
    }
    out.push_str("excludes=vmbr0,vmbr1,guest-nics\n");
    out
}

fn shell_word(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn write(path: &Path, contents: &str) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("failed to write {}", path.display()))
}
